services:
  user-service:
    build: ./services/user-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  product-service:
    build: ./services/product-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  order-service:
    build: ./services/order-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - USER_SERVICE_URL=http://user-service:8080
      - PRODUCT_SERVICE_URL=http://product-service:8081
    networks:
      - microservices-network
    depends_on:
      - user-service
      - product-service
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  microservices-network:
    driver: bridge
